### ISSUE TITLE
problem on mac

### ISSUE THREAD

**Issue by abcnow** [bibektimilsina000/FastAPI-PgStarterKit#1]
Thanks a lot for working on getting this live! I tried to run this on mac and I am getting this issue: any idea on how to fix this? Thanks in advance!

 Building 0.7s (2/3)                                      docker:desktop-linux
[+] Building 1.2s (3/3) FINISHED                             docker:desktop-linux
 => [fastapi-app internal] load build definition from Dockerfile             0.1s
 => => transferring dockerfile: 288B                                         0.0s
 => [fastapi-app internal] load .dockerignore                                0.1s
 => => transferring context: 111B                                            0.0s
 => ERROR [fastapi-app internal] load metadata for docker.io/library/python  0.6s
------
 > [fastapi-app internal] load metadata for docker.io/library/python:3.11-slim:
------
failed to solve: python:3.11-slim: error getting credentials - err: exit status 1, out: ``

**Comment by bibektimilsina000** [comment]
sucessfully running on mac m1 
please try 
```docker login```  first

**Comment by DungBuiDeveloper** [comment]
mac m1 :D working,  please buy new macboọk for fix them
