### ISSUE TITLE
SQLModel

### ISSUE THREAD

**Issue by gmos** [bibektimilsina000/FastAPI-PgStarterKit#10]
I want to include SQLModel in the backend to remove redundancies between models and schemas.  Would that fit your plans with the repo?

**Comment by bibektimilsina000** [comment]
Correct me if I'm wrong, but the objective of this project is to simplify the learning process for beginner programmers. Beginners often learn best through models and schemas. I believe that using SQLModel instead of straightforward models and schemas might complicate things for them.

**Comment by gmos** [comment]
SQLModel is a recent add-on to FastAPI.  Also authored by @tiangelo.
It unifies the Pydantic stuff in schemas and the SQLAlchemy stuff in models to a unified description.
They are just like the Pydantic schemas, but the ones with a table=True parameter also deliver the SQLAlchemy structures.

It avoids the redundancy between the two, thus minimizing the chance of both not matching properly.

I'll do a PR when finished, then you can have a look and decide if you want it or not.

**Comment by gmos** [comment]
Sorry, no SQLModel yet.  Tiangolo hasn't upgraded it to SQLAlchemy 2.x.x and Pydantic 2.x.x yet.  Seems to be high on his to-do list, but until then, bad luck.

**Comment by bibektimilsina000** [comment]
no worries we will fix it when it will relased
