### ISSUE TITLE
Cannot run the default package

### ISSUE THREAD

**Issue by lingyue328** [bibektimilsina000/FastAPI-PgStarterKit#3]
Hi. I got this error right after I installed  package and run docker-compose up --build.

`fastapi-app_1  | INFO:__main__:Initializing service
fastapi-app_1  | INFO:__main__:Starting call to '__main__.init', this is the 1st time calling it.
pgadmin        | NOTE: Configuring authentication for SERVER mode.
pgadmin        | 
pgadmin        | pgAdmin 4 - Application Initialisation
pgadmin        | ======================================
pgadmin        | 
pgadmin        | postfix/postlog: starting the Postfix mail system
pgadmin        | [2023-08-19 23:17:06 +0000] [1] [INFO] Starting gunicorn 20.1.0
pgadmin        | [2023-08-19 23:17:06 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
pgadmin        | [2023-08-19 23:17:06 +0000] [1] [INFO] Using worker: gthread
pgadmin        | [2023-08-19 23:17:06 +0000] [91] [INFO] Booting worker with pid: 91
fastapi-app_1  | ERROR:__main__:(psycopg2.OperationalError) connection to server at "db" (172.18.0.2), port 5432 failed: Connection timed out
fastapi-app_1  |        Is the server running on that host and accepting TCP/IP connections?
fastapi-app_1  | 
fastapi-app_1  | (Background on this error at: https://sqlalche.me/e/20/e3q8)
fastapi-app_1  | WARNING:__main__:Finished call to '__main__.init' after 129.312(s), this was the 1st time calling it.
fastapi-app_1  | INFO:__main__:Starting call to '__main__.init', this is the 2nd time calling it.`

**Comment by lingyue328** [comment]
I tested on my windows, it works. But still got this error in my ubuntu linux.

**Comment by lingyue328** [comment]
Some docker setting is wrong at the first. Reinstall docker helped.

**Comment by bibektimilsina000** [comment]
i am happy your problem fixed
