### ISSUE TITLE
get_current_active_superuser() does not seem to check that superuser is actually active

### ISSUE THREAD

**Issue by nsxsnx** [bibektimilsina000/FastAPI-PgStarterKit#5]
Hello,
Please, correct me if I'm wrong, but I believe here in **/backend/app/app/api/deps.py**:
```
def get_current_active_superuser(
    current_user: models.User = Depends(get_current_user),
) -> models.User:
```
we must depend on **get_current_active_user**, not **get_current_user** to make sure that superuser is active.

**Comment by bibektimilsina000** [comment]
yah you are right we must depend on get_current_active_user to check wether super user is active or not can you please create a pull request

**Comment by nsxsnx** [comment]
It's done
